version: '3.4'

services:   
      
  emulatorredis:
    image: redis:latest
    ports:
        - "6379:6379/tcp"   

  webappexample:
      build:
        context: ../.
        dockerfile: ./WebAppExample/Dockerfile   
        args:
          CONFIG: "Release"
      deploy:
        mode: replicated
        replicas: 5
      environment:
        Redis__RedisConnexionStrings__0: "emulatorredis:6379"
      ports:
        #HTTP
        - "9101-9105:8080"
        # HTTPS
        - "9106-9110:443" 

networks: 
  default: 
    name: local
    external: true
